sudo : false
language: python
python:
  - "3.7"
install:
  - pip3 install codecov
script:
  - cd ./lection_1 && coverage run units.py; cd ..
after_success:
  - codecov --token=d7280246-9435-4b35-b84d-8526acd28561
